services:
- type: web
  name: line-bot-python-flask
  env: python
  repo: https://github.com/ziyihong/ziyihong.github.io
  buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
  startCommand: cd examples/flask-echo;gunicorn app:app
  plan: free
  autoDeploy: false
  envVars:
  - key: MojkGXeag3xXX/lf3saxP/Afl3vUVkakM9yURbhc+peIKdCNt4r2O4CSmXH1qA3SOhOGvfhKW/i99OXJCfwsbOkijoi1QWqyECNEn/TPOLNYtSCtasHb9CURY70Y8WhVCIX3iHMhloEjycZsUVHVdQdB04t89/1O/w1cDnyilFU=
    sync: false
  - key: d35ed1ea2e5aeace00a4e07bf9a0028e
    sync: false
# - type: web
#   name: line-bot-python-flask-with-handler
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-echo;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-echo;gunicorn app_with_handler:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-flask-kitchensink
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/flask-kitchensink;pip install gunicorn -r requirements.txt
#   startCommand: cd examples/flask-kitchensink;gunicorn app:app
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-simple-server
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/simple-server-echo;pip install -r requirements.txt
#   startCommand: cd examples/simple-server-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
# - type: web
#   name: line-bot-python-aiohttp
#   env: python
#   repo: https://github.com/line/line-bot-sdk-python.git
#   buildCommand: cd examples/aiohttp-echo;pip install -r requirements.txt
#   startCommand: cd examples/aiohttp-echo;python app.py
#   plan: free
#   autoDeploy: false
#   envVars:
#   - key: LINE_CHANNEL_ACCESS_TOKEN
#     sync: false
#   - key: LINE_CHANNEL_SECRET
#     sync: false
